const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const details=$('#operatorDetails'), transcript=$('#callerTranscript'), suggestions=$('#suggestionsList'), summaryOutput=$('#summaryOutput'), summaryStatus=$('#summaryStatus'), chat=$('#chatMessages');
let aiEnabled=true, selected=[], history=JSON.parse(localStorage.getItem('pulsedesk-history')||'[]');
const samples={fire:{transcript:'Caller: There is a fire at the downtown apartment building. I can see smoke and people are inside. Please send help now.',services:['Fire Rescue','Ambulance']},collision:{transcript:'Caller: Two cars crashed at the intersection near the shopping center. One person is trapped and traffic is blocked in both directions.',services:['Police','Ambulance']},medical:{transcript:'Caller: My father is unconscious and having trouble breathing at home. We are near the community center and need an ambulance immediately.',services:['Ambulance']},robbery:{transcript:'Caller: Someone just robbed the convenience store on Main Street and ran toward the parking garage. No one appears injured.',services:['Police']},gas:{transcript:'Caller: We smell a strong gas odor in the office building and several people are coughing. We are evacuating toward the south entrance.',services:['Fire Rescue','Ambulance']},missing:{transcript:'Caller: My eight-year-old child is missing from the neighborhood park. They were last seen near the east playground wearing a blue jacket.',services:['Police']},water:{transcript:'Caller: A kayaker overturned near the north dock and is struggling in the water. I can see them about fifty feet from shore.',services:['Fire Rescue','Ambulance']},power:{transcript:'Caller: A power line is down across the road after the storm and sparks are visible near the intersection.',services:['Fire Rescue','Police']}};
function renderServices(){const box=$('#selectedServices');box.innerHTML=selected.length?selected.map(x=>`<span class="chip">${x}</span>`).join(''):'<span class="chip" style="background:#f7f7fa;color:#aaa">No services selected</span>';}
function analyze(){const text=(details.value+' '+transcript.value).toLowerCase();const noInjury=/no (one|person|people).*injur|no injuries|not injured/.test(text);let list=[];if(/fire|smoke|flame|burn/.test(text))list.push('Confirm the exact floor or unit and whether anyone is trapped.','Advise the caller to move away from smoke and never use an elevator.');if(/gun|weapon|shot|suspect/.test(text))list.push('Ask for the suspect description, direction of travel, and whether anyone is injured.');if(/medical|breath|heart|unconscious/.test(text)||(!noInjury&&/injur/.test(text)))list.push('Confirm responsiveness and breathing; ask if someone can safely begin first aid.');if(/crash|accident|vehicle|car/.test(text))list.push('Ask if anyone is trapped, if fuel is leaking, and whether traffic remains blocked.');if(!list.length)list=['Confirm the exact location, caller callback number, and immediate safety risks.','Ask how many people are involved and whether anyone is injured.'];suggestions.innerHTML=list.slice(0,3).map(x=>`<li>${x}</li>`).join('');}
function inferLocation(text){const m=text.match(/(?:at|near|on|in)\s+([a-z0-9 ,.'-]{3,60})/i);return m?m[1].replace(/[.!?].*$/,'').trim():'Location pending confirmation';}
function severity(text){if(/gun|weapon|shot|trapped|unconscious/.test(text))return 9;if(/fire|smoke/.test(text))return 8;if(/breath|heart|medical/.test(text))return 7;if(/crash|accident/.test(text))return 6;return 4;}
function buildSummary(){const text=(details.value+' '+transcript.value).trim();return {location:inferLocation(text),time:new Date().toLocaleString(),incident:details.value.trim()||transcript.value.trim()||'Unknown incident reported',severity:severity(text.toLowerCase()),services:selected.length?selected.join(', '):'Pending dispatch selection'};}
function addChat(message,type='ai'){const el=document.createElement('div');el.className=`chat-bubble ${type}`;const content=document.createElement('div');if(type==='ai'){const avatar=document.createElement('span');avatar.className='bubble-avatar';avatar.textContent='✦';el.appendChild(avatar);const name=document.createElement('strong');name.textContent='Pulse AI';content.appendChild(name);}const paragraph=document.createElement('p');paragraph.textContent=String(message).replace(/<[^>]*>/g,'');content.appendChild(paragraph);el.appendChild(content);chat.appendChild(el);chat.scrollTop=chat.scrollHeight;}
function assistantReply(q){const text=(q+' '+details.value+' '+transcript.value).toLowerCase();if(/next|ask|question/.test(q.toLowerCase()))return suggestions.firstElementChild?.textContent||'Ask for the exact location, caller callback number, and immediate safety risks.';if(/assess|severity|risk/.test(text)){const s=severity(text);return `I assess this as <b>${s}/10 priority</b> based on the information entered. Verify location, injuries, and hazards before dispatching.`;}if(/summary|report/.test(q.toLowerCase()))return 'I can generate a verified summary from the incident workspace. Make sure the location and caller details are confirmed first.';return 'I can help with next questions, risk assessment, or a call summary. Add more transcript detail for a stronger recommendation.';}
async function geminiReply(q){
  const context='Operator notes: '+(details.value||'None')+'\nCaller transcript: '+(transcript.value||'None')+'\nSelected services: '+(selected.join(', ')||'None');
  const apiBase=window.PULSEDESK_API_BASE;
  if(apiBase){
    try{
      const remote=await fetch(apiBase+'/api/gemini/stream',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({question:q,context:context})});
      if(!remote.ok)throw new Error('Render AI request failed');
      const reader=remote.body.getReader(),decoder=new TextDecoder();let buffer='',finalAnswer='';
      const pending=window.__pulsePending;
      while(true){
        const chunk=await reader.read();if(chunk.done)break;buffer+=decoder.decode(chunk.value,{stream:true});
        const events=buffer.split('\n\n');buffer=events.pop()||'';
        for(const event of events){
          const dataLine=event.split('\n').find(line=>line.startsWith('data: '));if(!dataLine)continue;
          try{const payload=JSON.parse(dataLine.slice(6));if(event.includes('event: agent')){if(pending)pending.querySelector('p').textContent=(payload.agent||'Agent')+' agent complete; reviewing...';}if(payload.answer){finalAnswer=payload.answer;if(pending)pending.querySelector('p').textContent=finalAnswer;}}catch(error){/* ignore malformed stream fragments */}
        }
      }
      return finalAnswer||assistantReply(q);
    }catch(error){return assistantReply(q)+'<br><small>Remote AI was unavailable, so I used the local assistant.</small>';}
  }
  return assistantReply(q);
}
function escapeHtml(value){return String(value).replace(/[&<>"']/g,character=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[character]));}
function renderHistory(){const list=$('#historyList');list.innerHTML=history.length?history.map((x,i)=>`<div class="history-row"><div><strong>${escapeHtml(x.incident.slice(0,80))}</strong><small>${escapeHtml(x.time)} · ${escapeHtml(x.services)} · Severity ${Number(x.severity)||0}/10</small></div><span class="badge subtle">Archived</span></div>`).join(''):'<div class="empty-summary"><div>◷</div><p>No saved incidents yet. Generate a summary to add the first report.</p></div>';}
$$('.service-btn').forEach(btn=>btn.addEventListener('click',()=>{const service=btn.dataset.service;if(selected.includes(service)){selected=selected.filter(x=>x!==service);btn.classList.remove('active')}else{selected.push(service);btn.classList.add('active')}renderServices();}));
[details,transcript].forEach(x=>x.addEventListener('input',analyze));
$('#simulateCall').addEventListener('click',()=>{const sampleKeys=Object.keys(samples);const sample=samples[sampleKeys[Math.floor(Math.random()*sampleKeys.length)]];details.value='';transcript.value=sample.transcript;selected=[];$$('.service-btn').forEach(x=>x.classList.remove('active'));sample.services.forEach(s=>{const b=$(`[data-service="${s}"]`);selected.push(s);b.classList.add('active')});renderServices();analyze();});
$('#clearTranscript').addEventListener('click',()=>{details.value='';transcript.value='';selected=[];$$('.service-btn').forEach(x=>x.classList.remove('active'));renderServices();analyze();summaryOutput.innerHTML='<div class="empty-summary"><div>✦</div><p>Generate a summary when you have enough information. Pulse AI will highlight what’s known and what still needs verification.</p></div>';summaryStatus.textContent='Ready for review';});
$('#generateSummary').addEventListener('click',()=>{if(!aiEnabled)return;summaryStatus.textContent='Verifying report…';const s=buildSummary();setTimeout(()=>{summaryOutput.innerHTML=`<div class="summary-box"><p><strong>Location:</strong> ${s.location}</p><p><strong>Time received:</strong> ${s.time}</p><p><strong>Dispatch:</strong> ${s.services}</p><p><strong>Severity:</strong> ${s.severity}/10 priority</p><p><strong>What happened:</strong> ${s.incident}</p><p class="verification"><strong>Verification:</strong> AI review complete. Operator must confirm all critical fields before dispatch.</p></div>`;summaryStatus.textContent='Verified summary ready';history.unshift(s);history=history.slice(0,10);localStorage.setItem('pulsedesk-history',JSON.stringify(history));renderHistory();addChat('Summary drafted and saved to incident history. Please verify every field before dispatch.');},500);});
function toggleAI(){aiEnabled=!aiEnabled;$('#aiToggle').textContent=aiEnabled?'ON':'OFF';$('#aiToggle').style.background=aiEnabled?'#e8faf2':'#f2f2f5';$('#aiToggle').style.color=aiEnabled?'#28bf82':'#999';$('#statusBadge').innerHTML=aiEnabled?'<i></i> AI active':'AI paused';$('#generateSummary').disabled=!aiEnabled;}
$('#aiToggle').addEventListener('click',toggleAI);async function sendChat(){const input=$('#chatInput'),q=input.value.trim();if(!q)return;addChat(q,'user');input.value='';addChat('Thinking…');const bubbles=chat.querySelectorAll('.chat-bubble');const pending=bubbles[bubbles.length-1];window.__pulsePending=pending;const response=await geminiReply(q);window.__pulsePending=null;pending.remove();addChat(response)}$('#sendChat').addEventListener('click',sendChat);$('#chatInput').addEventListener('keydown',e=>{if(e.key==='Enter')sendChat()});$$('.quick-prompts button').forEach(b=>b.addEventListener('click',()=>{ $('#chatInput').value=b.dataset.prompt;sendChat();}));
function showView(view){const dash=$('#dashboardView'),hist=$('#historyView');dash.classList.toggle('hidden',view!=='dashboard');hist.classList.toggle('hidden',view!=='history');$$('.nav-item').forEach(x=>x.classList.toggle('active',x.dataset.view===view));$('#pageTitle').textContent=view==='history'?'INCIDENT HISTORY':'COMMAND CENTER';$('#viewHeading').innerHTML=view==='history'?'Incident history <span>◷</span>':'Good evening, dispatcher <span>✦</span>';if(view==='history')renderHistory();}$$('.nav-item').forEach(b=>b.addEventListener('click',()=>showView(b.dataset.view)));$('#newIncident').addEventListener('click',()=>{showView('dashboard');$('#clearTranscript').click();details.focus()});$('#clearHistory').addEventListener('click',()=>{history=[];localStorage.removeItem('pulsedesk-history');renderHistory()});renderServices();analyze();renderHistory();